### ISSUE TITLE
Pull-requests created by github api aren't triggering CI builds

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/gha-pull-request#8]
e.g. gha-update-js run https://github.com/silverstripe/silverstripe-mfa/pull/505

There was no CI build automatically triggered

Likely the same issue seen in gha-merge-up where a CI build wasn't triggered after merging up a branch

---

**Example workflow run - https://github.com/emteknetnz/silverstripe-tagfield/actions/runs/5885305010**

**Example PR created - https://github.com/emteknetnz/silverstripe-tagfield/pull/13**

## PRs
- https://github.com/silverstripe/gha-pull-request/pull/9
- https://github.com/silverstripe/gha-trigger-ci/pull/1

**Comment by emteknetnz** [comment]
Trigger using the GITHUB_TOKEN will prevent further actions from being triggered
https://github.com/peter-evans/create-pull-request/issues/48#issuecomment-536204092

It's an intentional design decision from github to prevent infinite loop situations
https://github.com/peter-evans/create-pull-request/issues/48#issuecomment-537478081

Not sure how to resolve this.  Putting a PAT (personal-access-token) in every repo seems very undesirable.  If it's possible to do an org wide PAT shared with every repo that's a possibility

In gha-merge-up we can just use the API to manually trigger a new build on the branch.  However in this situation it's for pull-requests .. so you'd need to get the API to trigger a build for a pull-request? I don't think that's possible

**Comment by emteknetnz** [comment]
On this pull-request https://github.com/silverstripe/silverstripe-totp-authenticator/pull/132 - Using the UI I manually triggering a CI build against the pull-request branch https://github.com/silverstripe/silverstripe-totp-authenticator/actions/runs/5884330658 - however the builds don't show up automatically above the merge button

Possibly we could add in a link to the CI build with some all caps text saying CHECK CI BUILD HERE BEFORE MERGING and some more text explaining why the workaround exists

**Comment by emteknetnz** [comment]
On this pull-request https://github.com/silverstripe/silverstripe-tagfield/pull/254 - I closed it first, then started the CI build and then re-opened the pull-requests - this time builds did show up automatically

While this is good, in this context however both the pull-request and the CI is created using API calls so there's no guarantee about which ordered they'll get created, meaning that probably sometimes the builds would show and other times they wouldn't

**Comment by emteknetnz** [comment]
I did a third test on this pull-request https://github.com/silverstripe/silverstripe-login-forms/pull/150 - I manually triggered the ci build, then I closed and re-opened the pull-request.  The builds showed up automatically.  This implies we can provide instructions on the pull-request to close and re-open the pull-request to get the builds to show

**Comment by GuySartorelli** [comment]
Reassigned to @emteknetnz to check (if there's an easy way to do so) that the merged PRs have resolved the problem.
Note that while `gha-pull-requests` got its patch tag, the `v1` tag hasn't been automatically updated so you'll need to do that first. I left that undone so you could see it for the sake of the message I just put in slack.

**Comment by emteknetnz** [comment]
Have manually updated the v1 tag. Going forward this should be solved by https://github.com/silverstripe/.github/issues/94
